// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7oT0Fnm7qCFegH8BPmp4rn1yNQJP1ODo',
    appId: '1:436543272299:web:709affeb10bf34249e482e',
    messagingSenderId: '436543272299',
    projectId: 'csms-staging-179d8',
    authDomain: 'csms-staging-179d8.firebaseapp.com',
    storageBucket: 'csms-staging-179d8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_gbc7neVXzFsyN92Q6A2DpIl1cWjgw7w',
    appId: '1:436543272299:android:2e28a79c605379079e482e',
    messagingSenderId: '436543272299',
    projectId: 'csms-staging-179d8',
    storageBucket: 'csms-staging-179d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8jMh0JmaTtqKxNg9hxFCyv3CV4m6YmW0',
    appId: '1:436543272299:ios:efe1f9660d5cff689e482e',
    messagingSenderId: '436543272299',
    projectId: 'csms-staging-179d8',
    storageBucket: 'csms-staging-179d8.firebasestorage.app',
    iosBundleId: 'com.live.csms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8jMh0JmaTtqKxNg9hxFCyv3CV4m6YmW0',
    appId: '1:436543272299:ios:8c6228318ab3716d9e482e',
    messagingSenderId: '436543272299',
    projectId: 'csms-staging-179d8',
    storageBucket: 'csms-staging-179d8.firebasestorage.app',
    iosBundleId: 'com.example.csms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7oT0Fnm7qCFegH8BPmp4rn1yNQJP1ODo',
    appId: '1:436543272299:web:9133a59a2ade58739e482e',
    messagingSenderId: '436543272299',
    projectId: 'csms-staging-179d8',
    authDomain: 'csms-staging-179d8.firebaseapp.com',
    storageBucket: 'csms-staging-179d8.firebasestorage.app',
  );
}
