// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSOQgjl5hL7wSXbnFQ9bHX_WBHoXQDp18',
    appId: '1:1034933865940:web:3e0cdcfdf8d6e630369a41',
    messagingSenderId: '1034933865940',
    projectId: 'csms-b03e1',
    authDomain: 'csms-b03e1.firebaseapp.com',
    databaseURL: 'https://csms-b03e1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'csms-b03e1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCosq6Mk5Yam7cm7LJGe2WNSs_TIhSV9VU',
    appId: '1:1034933865940:android:4fc91b536d6e4f3c369a41',
    messagingSenderId: '1034933865940',
    projectId: 'csms-b03e1',
    databaseURL: 'https://csms-b03e1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'csms-b03e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfngldpkJBSXCwwH5blARH0yF-bDsCE0Q',
    appId: '1:1034933865940:ios:ed536875546a0219369a41',
    messagingSenderId: '1034933865940',
    projectId: 'csms-b03e1',
    databaseURL: 'https://csms-b03e1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'csms-b03e1.firebasestorage.app',
    iosBundleId: 'com.live.csms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfngldpkJBSXCwwH5blARH0yF-bDsCE0Q',
    appId: '1:1034933865940:ios:e9335613def6566d369a41',
    messagingSenderId: '1034933865940',
    projectId: 'csms-b03e1',
    databaseURL: 'https://csms-b03e1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'csms-b03e1.firebasestorage.app',
    iosBundleId: 'com.example.csms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSOQgjl5hL7wSXbnFQ9bHX_WBHoXQDp18',
    appId: '1:1034933865940:web:afa900f8ce73c38c369a41',
    messagingSenderId: '1034933865940',
    projectId: 'csms-b03e1',
    authDomain: 'csms-b03e1.firebaseapp.com',
    databaseURL: 'https://csms-b03e1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'csms-b03e1.firebasestorage.app',
  );

}