// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFJ2wfsTeYz_S1ZoZuGsMutx_EH1MtIHc',
    appId: '1:192075236305:web:8354328f26368623cb96f0',
    messagingSenderId: '192075236305',
    projectId: 'csms-a87ef',
    authDomain: 'csms-a87ef.firebaseapp.com',
    databaseURL: 'https://csms-a87ef-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'csms-a87ef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAic-rPCw_FL8DY6EXnlz20KITdsB21v98',
    appId: '1:192075236305:android:a487b3189d7ba2d2cb96f0',
    messagingSenderId: '192075236305',
    projectId: 'csms-a87ef',
    databaseURL: 'https://csms-a87ef-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'csms-a87ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYuF8nr0lY1Vp7Dfyw1w5qqQqmhiZjnEg',
    appId: '1:192075236305:ios:10d5c4c96f3b8877cb96f0',
    messagingSenderId: '192075236305',
    projectId: 'csms-a87ef',
    databaseURL: 'https://csms-a87ef-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'csms-a87ef.firebasestorage.app',
    iosBundleId: 'com.live.csms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYuF8nr0lY1Vp7Dfyw1w5qqQqmhiZjnEg',
    appId: '1:192075236305:ios:0948bbd744c76270cb96f0',
    messagingSenderId: '192075236305',
    projectId: 'csms-a87ef',
    databaseURL: 'https://csms-a87ef-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'csms-a87ef.firebasestorage.app',
    iosBundleId: 'com.example.csms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFJ2wfsTeYz_S1ZoZuGsMutx_EH1MtIHc',
    appId: '1:192075236305:web:23622a50b3564844cb96f0',
    messagingSenderId: '192075236305',
    projectId: 'csms-a87ef',
    authDomain: 'csms-a87ef.firebaseapp.com',
    databaseURL: 'https://csms-a87ef-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'csms-a87ef.firebasestorage.app',
  );

}